# Generated by Django 3.0.6 on 2020-10-10 19:41

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('poster', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=500)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
