# Generated by Django 2.2.3 on 2020-10-21 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav_svideos', to=settings.AUTH_USER_MODEL),
        ),
    ]
