# Generated by Django 3.0.6 on 2020-10-19 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Western', 'Western'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('War', 'War')], default='Fiction', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('movie', 'Movies'), ('show', 'TV Show'), ('series', 'TV Series')], default='movie', max_length=20),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='requirement_video_likes', to='storage_video.Video')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='storage_video.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='requirement_video_dis_likes', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dis_likes', to='storage_video.Video')),
            ],
        ),
    ]
