# Generated by Django 3.0.6 on 2020-10-24 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_video', '0002_auto_20201024_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav_svideos', to=settings.AUTH_USER_MODEL),
        ),
    ]
