# Generated by Django 3.0.6 on 2020-10-19 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_video', '0002_auto_20201019_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='users',
            field=models.ManyToManyField(related_name='requirement_video_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
