# Generated by Django 3.0.6 on 2020-10-24 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_video', '0004_video_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='currentUser',
            field=models.ManyToManyField(related_name='time', to=settings.AUTH_USER_MODEL),
        ),
    ]
