# Generated by Django 3.0.6 on 2020-10-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_video', '0005_video_currentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='currentUser',
        ),
    ]
