# Generated by Django 3.0.6 on 2020-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_video', '0006_remove_video_currentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('video_title', models.CharField(max_length=100)),
                ('currentTime', models.IntegerField(default=0)),
            ],
        ),
    ]
