# Generated by Django 3.0.6 on 2020-10-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_video', '0007_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='currentTime',
            field=models.FloatField(default=0.0),
        ),
    ]
