# Generated by Django 3.0.6 on 2020-10-24 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav_yvideos', to=settings.AUTH_USER_MODEL),
        ),
    ]
