# Generated by Django 3.0.6 on 2020-10-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
