# Generated by Django 2.2.3 on 2020-10-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Western', 'Western'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('War', 'War')], default='Fiction', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('movie', 'Movies'), ('show', 'TV Show'), ('series', 'TV Series')], default='movie', max_length=20),
        ),
    ]
