# Generated by Django 3.0.6 on 2020-10-24 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_video', '0002_item_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='item',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.AddField(
            model_name='item',
            name='dislikes',
            field=models.ManyToManyField(related_name='ydislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(related_name='ylikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
